[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./pocketbase serve --http=0.0.0.0:$PORT --dir=./pb_data --migrationsDir=./pb_migrations --hooksDir=./pb_hooks"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
